# Author: Samar Gill
# File: docker-compose.yml
# Description: Docker stack for KU Campus Exchange
version: "3.9"

services:
  db:
    image: postgres:14
    container_name: my_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: kucampus
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data

  php:
    build: .
    container_name: php_fpm
    volumes:
      - ./web:/var/www/html
    depends_on:
      - db

  nginx:
    image: nginx:alpine
    container_name: ku_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./web:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    depends_on:
      - php
    command: ["nginx", "-g", "daemon off;"]

  certbot:
    image: certbot/certbot
    container_name: ku_certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-www:/var/www/certbot
    entrypoint: >
      sh -c "trap exit TERM; while :; do
             certbot renew --webroot -w /var/www/certbot;
             sleep 12h & wait $${!};
             done"

volumes:
  pgdata:
  certbot-etc:
  certbot-www:
